name: "snyk code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test --sarif > snyk-sarif2.json
        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Ignore deps test
        run: snyk auth {{ secrets.SNYK_TOKEN }}
        run: snyk ignore --id='SNYK-PYTHON-CERTIFI-5805047' --expiry='2024-11-24' --reason='testing' -d
        env:
          SNYK_TOKEN: ${{ steps.secrets.outputs.token }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-sarif2.json
